_BASE_: DVIS_Plus_Online_R50.yaml
MODEL:
  META_ARCHITECTURE: "DVIS_Plus_offline"
  REFINER:
    USE_CL: False
SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (28000,)
  MAX_ITER: 40000

INPUT:
  SAMPLING_FRAME_NUM: 5
  SAMPLING_FRAME_RANGE: 2
  REVERSE_AGU: True
  CROP:
    ENABLED: True
  PSEUDO:
    CROP:
      ENABLED: True
OUTPUT_DIR: './DVIS_Plus_Offline_R50_HybridOR_temporal_offline_52_reverseagu_withsimstation'